import { Box, Heading, Flex, Image, Text } from "@chakra-ui/react"
export default function Footer() {
    return (
        <Box
        w={["full","full","1920px","full"]}
            h="100%"
            bgColor="white"
            mb={24}        
        >
            <Flex
                 w={["480px", "480px", "1180px","1280px"]}
                mx="auto"
            >
                <Flex
                    w="430px"
                    my="23px"
                >
                    <Image
                        src="./assets/Emblema.png"
                        h="154px"
                        w="154px"
                        mr="20px"
                        alt="Emblema"
                    />
                    <Heading
                        as="h2"
                        h="154px"
                        w="250px"
                        fontFamily="Zector"
                        fontWeight="normal"
                        fontSize="50px"
                        lineHeight="57px"
                        mt="19px"
                        display={["none","none","block"]}
                    >
                        Oriental Wing Shun
                    </Heading>
                </Flex>
                <Box
                    my={["23px","23px","67.5px"]}
                    w="250px"
                    mx="auto"
                    display={["block","block", "flex"]}
                >
                    <Image
                        src="./assets/INSTA_ICON.png"
                        h={["50px","50px","65px"]}
                        w={["50px","50px","65px"]}
                        mr="25px"
                        mb="5px"
                    />
                    <Image
                        src="./assets/FACE_ICON.png"
                        h={["50px","50px","65px"]}
                        w={["50px","50px","65px"]}
                        mr="25px"
                        mb="5px"
                    />
                    <Image
                        src="./assets/WHATS_ICON-1.png"
                        h={["50px","50px","65px"]}
                        w={["50px","50px","65px"]}
                    />
                </Box>
                <Box
                    mt="60px"
                    ml={["-25px","-25px",0]}
                    w="333px"
                    h="100%"
                >
                    <Text
                        fontFamily="Zector"
                        fontWeight="normal"
                        fontSize="20px"
                        lineHeight="23px"
                        textAlign="right"
                        color="black"
                        textTransform="uppercase"
                        w="170px"
                    >
                        Desenvolvido por
                    </Text>
                    <Image
                        src="./assets/logo.png" 
                        w="333px"
                        h="51px"
                    />
                </Box>
            </Flex>
        </Box>
    )
}